* ipython-shell-send

This package adds extra IPython functionality for Emacs' python.el.
It adds the following two features:
1. Connect to and run existing jupyter consoles, e.g. on a remote server.
2. Allow IPython magic in code blocks sent to the inferior Python buffer.

The first feature is provided by the function ~ipython-shell-send/run-jupyter-existing~. Calling this function will prompt for an existing jupyter kernel, and then run it in the inferior Python buffer from ~python.el~. To run a remote jupyter kernel, call ~ipython-shell-send/run-jupyter-existing~ from within a Tramp buffer visiting the remote machine.

The second feature is provided by the following functions:

#+BEGIN_SRC emacs-lisp
  ipython-shell-send-buffer
  ipython-shell-send-region
  ipython-shell-send-defun
#+END_SRC

which are analogous to their counterparts ~python-shell-*~ from ~python.el~, except that they can handle IPython magic commands such as ~!ls~ or ~%timeit~.

** Example: running a remote Jupyter kernel in Emacs

First, start a Jupyter console named "my-remote-console" on the remote machine:

#+BEGIN_SRC sh
  jupyter --console -f my-remote-console
#+END_SRC

Then in emacs, visit any file on the remote machine, e.g. =C-x C-f /scp:username@remotehost:~=. Then call =M-x ipython-shell-send/run-jupyter-existing=, and enter "my-remote-console" at the prompt. This will create the usual inferior =*Python*= buffer, but connected to a remote Jupyter console instead of starting a new Python subprocess.
